development:
  adapter: mysql2
  encoding: utf8
  database: claim_development
  pool: 5
  username: root
  password: isiri
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: claim_development
  pool: 5
  username: root
  password: ayusroot!123
  socket: /var/run/mysqld/mysqld.sock